// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicLibraryWebAPI.Data;

#nullable disable

namespace MusicLibraryWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230718211102_final")]
    partial class final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MusicLibraryWebAPI.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Sea Change",
                            Artist = "Hello Moto",
                            Genre = "Crunk",
                            ReleaseDate = new DateTime(2023, 7, 18, 15, 11, 2, 651, DateTimeKind.Local).AddTicks(9780),
                            Title = "Across The Way"
                        },
                        new
                        {
                            Id = 2,
                            Album = "World's Apart",
                            Artist = "Journey",
                            Genre = "rock",
                            ReleaseDate = new DateTime(2023, 7, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Promise Broken"
                        },
                        new
                        {
                            Id = 3,
                            Album = "Sea Change",
                            Artist = "Beck",
                            Genre = "Alternative",
                            ReleaseDate = new DateTime(2023, 7, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Paper Tiger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
